services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - my_rasp_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - my_rasp_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - my_rasp_network

  common_infra:
    image: richie31/common-infra-python-library
    container_name: common_infra
    env_file:
      - /home/richie/private-secrets/common_infra/.env
    ports:
      - "5003:5003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
    volumes:
      - mysql_ubuntu_rasp_device:/dumps
    networks:
      - my_rasp_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - my_rasp_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - /home/richie/private-secrets/mysql/.env
    volumes:
      - mysql_ubuntu_rasp_device:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_rasp_network

networks:
  my_rasp_network:
    driver: bridge

volumes:
  mysql_ubuntu_rasp_device:
    external: true
  grafana-storage:
    external: false
  prometheus_data: {}