---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-infra-secret
  namespace: common-infra
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBzT0R0UeEImzStprsixAkIRXsR+GqZgfllwSxhoyF3t0rMbCjUajTNJrvufshLMMM8cblBis6VygnAHYqDsujkQWNOKPN5fESRnE3h8bYWJ4bQ1xuPXRtv1KStapwvvU2JMWY6MNS6wgp7pRH0xT+NGptotTSJoVK3nSdm+p6//RWaLYtfzZZuDpE65NYzxR252vNcuo3+nexRzBvgpr4InBlZLmK40gazwLXUOu92opN0589QBYQFtK6bwz7zpfVQbaolESVSJpRfFAyT3nf8T5dmQbrS8BAkX7AG4RmqZXehO/5d4OAW6fOZlUXH3JMsLmP/Lt3xz/E8ZlQ9lkLmAlj5rqdSykmnmli+78ynYPVPTRzffdUX4445JRaaTpcX+GpojEtGL4ORzo/YMpu95OT7/IVvnY6E2PAMXT+s2Sn0TB0qvoOFMyC/K2Lf/oIpUTYoP/2CdBQ50scYPDPubX+RQvl/rDeq80Pq3o2pF+utSp+NL5jz0Fc9iZkT7ICZTcNNqI7YfxLWKvQ7reXC0VOEs9fuZxUEuDDUdUCkCgPmMhVh6+OOsDEoRIXx65ZpWHxqqqpvfeMkE7E6hUWbhO2YEcSyTthyhMMtnkoggis2OFhFlpiLXs4nHnJCChI4J42uJG5VFEfU9uPACrRDdhS4seIQgvJcNg2yoHtaWO/+8vogYHntG3DAPZFquZ6pH/Jf7PhQTzo1kqEj5A==
    MYSQL_USER: AgAIOuEh6qji67DqDW6SnuuNPC3dfAHDGUA5HnCCTEiRlAA+R0C183H6rqmRBKx+y3YZTdBJMQM9muTTLSSPGel1dmY9MoxXV8GJxlQMJrpYiyVJ6QhOn158lVfxvSCzKTQHqtu4XKJkrkCa6mrjaC2JhWvjGrXOdMRUTzEQ+6DLRMmPhKnLr03Bor8VIflmvShPukLcS/34AzmINv/PDuF2ky+v0s4X9UDrSw7ojTnmAzgMZHgzblrKweASCKBR9ezT8yOu3wT5ckSVJV3qhb1oABsqlD3vbDIfqwDo8RjZzF3fiKnk2RNj/LZf0RJqs+QVhar1KSdqY208DQ/dYs7aa1AvpAHbaiyI3ghY05tyz8gzxHDwCNGnovG4eIIrZJ/FA5dVyN9dIuPgJk9Ie3Sslzhqxa/CojE704G1icL7/YHzgJP/1zDqVBYwzrbXbnKhxM7dsDSNz+EwcgorwaH9bMbnr9B9TLkNXTlK7ggRM9dJrSKh98eEChqwQ5mTS1fVQKc4glJnCKAJKNM859cNRvonHYuEMoOnBWgKEfmUlqOMQZRa62ibgUNgPm2QrSjU3qDMEddxd9N7DAQ0SkgswpNToJR3YSGh5uUvmBcpxru+4AYYNEqfknmhm6cv9B87Yzw9VDG0tkqf3xtmSF2pJs+KnMWPYUwSjgtHhqmQQQgbub0AklLBk7d9ddX331099I0O
  template:
    metadata:
      name: common-infra-secret
      namespace: common-infra
    type: Opaque
