apiVersion: v1
kind: Service

metadata:
  name: common-infra-service
  namespace: common-infra

spec:
  type: NodePort

  selector:
    app: common-infra-app

  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30080