name: On PR Merge - Build and Deploy

on:
  pull_request:
    types:
      - closed  # Trigger when a PR is closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: richie31  # Replace with your Docker Hub username
      DOCKER_IMAGE: common-infra-python-library:latest  # Define the image name

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies for building the Python package
      - name: Install Build Tools
        run: |
          python3 -m pip install --upgrade --user pip setuptools wheel twine
    
      # Step 3: Build the Python package
      - name: Build Python Package
        run: |
          python3 setup.py sdist bdist_wheel

      # Step 4: Upload the package to the self-hosted PyPI server
      - name: Upload to Self-Hosted PyPI
        run: |
          twine upload --repository-url $PYPI_URL -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME --password-stdin <<< $DOCKER_PASSWORD

      # Step 6: Build the Docker image for common_infra
      - name: Build Docker Image for common_infra
        run: |
          docker compose build common_infra # Correct command to build the specific service's image
        working-directory: . # IMPORTANT: Adjust this if docker-compose.yml is not in the root

      # Step 7: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}

      # Step 8: Bring down 'common_infra' service (stops and removes container)
      - name: Bring down 'common_infra' service
        run: |
          if docker compose ps -q common_infra &>/dev/null; then
            docker compose down common_infra
          else
            echo "Service 'common_infra' is not running."
          fi
        working-directory: . # IMPORTANT: Adjust this if docker-compose.yml is not in the root

      # Step 9: Remove Old Docker Image
      - name: Remove Old Docker Image
        run: |
          docker rmi ${DOCKER_USERNAME}/${DOCKER_IMAGE} || true
          docker image prune -f

      # Step 10: Start New Container for 'common_infra' service
      - name: Start 'common_infra' service
        run: |
          # Use docker compose up with --build flag here to ensure it uses the latest build
          docker compose up -d --build common_infra
        working-directory: .