name: On PR Merge - Build and Deploy

on:
  pull_request:
    types:
      - closed  # Trigger when a PR is closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true  # Only run if the PR was merged
    runs-on: self-hosted  # Use your self-hosted runner or GitHub-hosted runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Install dependencies for building the Python package
      - name: Install Build Tools
        run: |
          python3 -m pip install --upgrade --user pip setuptools wheel twine --prefix /home/github-runner/custom-python-packages

      # add the directory to PATH
      - name: Add Custom Python Path
        run: |
          export PATH=/home/github-runner/custom-python-packages/bin:$PATH
          
      # Step 4: Build the Python package
      - name: Build Python Package
        run: |
          python3 setup.py sdist bdist_wheel


      # Step 6: Upload the package to the self-hosted PyPI server
      - name: Upload to Self-Hosted PyPI
        env:
          TWINE_USERNAME: $PYPI_USERNAME
          TWINE_PASSWORD: $PYPI_PASSWORD
        run: |
          twine upload --repository-url $PYPI_URL dist/*

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME --password-stdin <<< $DOCKER_PASSWORD

      # Step 8: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:latest .

      # Step 9: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGE_NAME:latest

      # Step 10: Stop the currently running common_infra container
      - name: Stop the currently running common_infra container
        run: |
          if [ "$(docker ps -q -f name=common_infra_abstraction_layer)" ]; then
            docker stop common_infra_abstraction_layer;
          fi
          docker rm common_infra_abstraction_layer || true

      # Step 11: Start a new common_infra container with the latest image
      - name: Start a new common_infra container with the latest image
        run: |
          docker run -d \
            --name common_infra_abstraction_layer \
            --network my_rasp_network \
            -p 5003:5003 \
            $DOCKER_IMAGE_NAME:latest
