name: On PR Merge - Build and Deploy

on:
  pull_request:
    types:
      - closed  # Trigger when a PR is closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: richie31  # Replace with your Docker Hub username
      DOCKER_IMAGE: common-infra-python-library:latest  # Define the image name

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies for building the Python package
      - name: Install Build Tools
        run: |
          python3 -m pip install --upgrade --user pip setuptools wheel twine
    
      # Step 3: Build the Python package
      - name: Build Python Package
        run: |
          python3 setup.py sdist bdist_wheel

      # Step 4: Upload the package to the self-hosted PyPI server
      - name: Upload to Self-Hosted PyPI
        run: |
          echo $PYPI_URL
          twine upload --repository-url $PYPI_URL -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME --password-stdin <<< $DOCKER_PASSWORD

      # Step 6: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE} .

      # Step 7: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}

      # Step 8: Stop and Remove Existing Container
      - name: Stop and Remove Existing Container
        run: |
          if [ "$(docker ps -q -f name=common_infra)" ]; then
            docker stop common_infra
            docker rm common_infra
          fi

      # Step 9: Remove Old Docker Image
      - name: Remove Old Docker Image
        run: |
          docker rmi ${DOCKER_USERNAME}/${DOCKER_IMAGE} || true
          docker image prune -f

      # Step 10: Start New Container
      - name: Start New Container
        run: |
          docker run -d -p 5003:5003 \
            --name common_infra \
            --network my_rasp_network \
            --restart unless-stopped \
            ${DOCKER_USERNAME}/${DOCKER_IMAGE}
