name: On PR Merge - Build and Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_USERNAME: richie31
      DOCKER_IMAGE: common-infra-python-library:latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Python package
      - name: Build Python Package
        run: |
          python3 -m pip install --upgrade --user pip setuptools wheel twine
          python3 setup.py sdist bdist_wheel

      # Step 3: Upload the package to the self-hosted PyPI server
      - name: Upload to Self-Hosted PyPI
        run: |
          twine upload --repository-url $PYPI_URL -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME --password-stdin <<< $DOCKER_PASSWORD

      # Step 5: Bring down 'common_infra' service (stops and removes container)
      - name: Bring down 'common_infra' service
        run: |
          if docker compose ps -q common_infra &>/dev/null; then
            docker compose down common_infra
          else
            echo "Service 'common_infra' is not running."
          fi
        working-directory: .

      # Step 6: Remove Old Docker Image
      - name: Remove Old Docker Image
        run: |
          docker rmi ${DOCKER_USERNAME}/${DOCKER_IMAGE} || true
          docker image prune -f

      # Step 7: Build the Docker image for common_infra
      - name: Build Docker Image for common_infra
        run: |
          docker compose build common_infra
        working-directory: .

      # Step 8: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}

      # Step 9: Start New Container for 'common_infra' service
      - name: Start New Container
        run: |
          docker compose up -d --build common_infra
        working-directory: .
